### ISSUE TITLE
CMake Error at apps/CMakeLists.txt:84 (add_executable):

### ISSUE THREAD

**Issue by nal10** [BlueBrain/Ultraliser#52]
Getting this error when trying to install using your wiki instructions. I have a previous version install on another machine that did not have this error and I see that the apps/CMakeLists.txt file has been updated since my last install with additions relating to testEdgeCollape

`
CMake Error at apps/CMakeLists.txt:84 (add_executable):
  Cannot find source file:

    testEdgeCollapse.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at apps/CMakeLists.txt:84 (add_executable):
  No SOURCES given to target: testEdgeCollapse
`

**Comment by marwan-abdellah** [comment]
@nal10 Thanks for reporting this bug. The CMakeLists files has been fixed. You can pull and re-compile. Don't forget to delete the CMakeCache. 

Thanks,
